import type { Dev, Devs, MiscCredit } from "../types/misc.js";

export const CommonDevs: Record<Devs, Dev> = {
  DuckySoLucky: { username: "duckysolucky", id: "486155512568741900", iconURL: "https://imgur.com/tgwQJTX.png", type: "Maintainer" },
  Kathund: { username: ".kathund", github: "kathund", id: "1276524855445164098", iconURL: "https://i.imgur.com/uUuZx2E.png", type: "Maintainer" },
  GeorgeFilos: { username: "george_filos", github: "georgefilos", id: "177083022305263616", iconURL: "https://i.imgur.com/YdxW048.png", type: "Contributor" },
  Zickles: { username: "zickles", id: "468043261911498767", iconURL: "https://i.imgur.com/vw8SAq4.png", type: "Contributor" }
};

export const MiscCredits: MiscCredit[] = [
  { name: "discord.js", description: "Handles the discord part of this project", link: "discord.js.org" },
  { name: "mineflayer", description: "Handles the minecraft part of this project", link: "prismarinejs.github.io/mineflayer" },
  { name: "Hypixel API", description: "It's the Hypixel API? What else would I say", link: "api.hypixel.net" },
  { name: "Hypixel-API-Reborn", description: "Handles all processing of the Hypixel API", link: "github.com/Hypixel-API-Reborn/hypixel-api-reborn" },
  { name: "Mowojang API", description: "Handles UUID <--> Username conversions", link: "mowojang.matdoes.dev" },
  { name: "DawJaw", description: "Jacob contests tracking", link: "dawjaw.net" },
  { name: "Soopy", description: "SoopyV2 commands", link: "soopy.dev" }
];

export const PlayerVariableStatsKeysString = ["username", "guildRank", "guildName", "duelsDivision"] as const;
export const PlayerVariableStatsKeysNumber = [
  "level",
  "karma",
  "achievementPoints",

  "bedwarsStar",
  "bedwarsTokens",
  "bedwarsKills",
  "bedwarsDeaths",
  "bedwarsKDRatio",
  "bedwarsFinalKills",
  "bedwarsFinalDeathss",
  "bedwarsFinalKDRatio",
  "bedwarsWins",
  "bedwarsLosses",
  "bedwarsWLRatio",
  "bedwarsBedsBroken",
  "bedwarsBedsLost",
  "bedwarsBedsBLRatio",
  "bedwarsPlayedGames",

  "bedwarsSoloKills",
  "bedwarsSoloDeaths",
  "bedwarsSoloKDRatio",
  "bedwarsSoloFinalKills",
  "bedwarsSoloFinalDeathss",
  "bedwarsSoloFinalKDRatio",
  "bedwarsSoloWins",
  "bedwarsSoloLosses",
  "bedwarsSoloWLRatio",
  "bedwarsSoloBedsBroken",
  "bedwarsSoloBedsLost",
  "bedwarsSoloBedsBLRatio",
  "bedwarsSoloPlayedGames",

  "bedwarsDoublesKills",
  "bedwarsDoublesDeaths",
  "bedwarsDoublesKDRatio",
  "bedwarsDoublesFinalKills",
  "bedwarsDoublesFinalDeathss",
  "bedwarsDoublesFinalKDRatio",
  "bedwarsDoublesWins",
  "bedwarsDoublesLosses",
  "bedwarsDoublesWLRatio",
  "bedwarsDoublesBedsBroken",
  "bedwarsDoublesBedsLost",
  "bedwarsDoublesBedsBLRatio",
  "bedwarsDoublesPlayedGames",

  "bedwarsThreesKills",
  "bedwarsThreesDeaths",
  "bedwarsThreesKDRatio",
  "bedwarsThreesFinalKills",
  "bedwarsThreesFinalDeathss",
  "bedwarsThreesFinalKDRatio",
  "bedwarsThreesWins",
  "bedwarsThreesLosses",
  "bedwarsThreesWLRatio",
  "bedwarsThreesBedsBroken",
  "bedwarsThreesBedsLost",
  "bedwarsThreesBedsBLRatio",
  "bedwarsThreesPlayedGames",

  "bedwarsFoursKills",
  "bedwarsFoursDeaths",
  "bedwarsFoursKDRatio",
  "bedwarsFoursFinalKills",
  "bedwarsFoursFinalDeathss",
  "bedwarsFoursFinalKDRatio",
  "bedwarsFoursWins",
  "bedwarsFoursLosses",
  "bedwarsFoursWLRatio",
  "bedwarsFoursBedsBroken",
  "bedwarsFoursBedsLost",
  "bedwarsFoursBedsBLRatio",
  "bedwarsFoursPlayedGames",

  "bedwars4v4Kills",
  "bedwars4v4Deaths",
  "bedwars4v4KDRatio",
  "bedwars4v4FinalKills",
  "bedwars4v4FinalDeathss",
  "bedwars4v4FinalKDRatio",
  "bedwars4v4Wins",
  "bedwars4v4Losses",
  "bedwars4v4WLRatio",
  "bedwars4v4BedsBroken",
  "bedwars4v4BedsLost",
  "bedwars4v4BedsBLRatio",
  "bedwars4v4PlayedGames",

  "skywarsStar",
  "skywarsCoins",
  "skywarsTokens",
  "skywarsSouls",
  "skywarsOpals",
  "skywarsKills",
  "skywarsDeaths",
  "skywarsKDRatio",
  "skywarsWins",
  "skywarsLosses",
  "skywarsWLRatio",
  "skywarsPlayedGames",

  "duelsKills",
  "duelsDeaths",
  "duelsKDRatio",
  "duelsWins",
  "duelsLosses",
  "duelsWLRatio",
  "duelsPlayedGames",

  "skyblockBank",
  "skyblockPurse",
  "skyblockLevel",

  "skyblockSkillsAverageLevel",
  "skyblockSkillsNonCosmeticAverageLevel",
  "skyblockSkillsFarmingLevel",
  "skyblockSkillsMiningLevel",
  "skyblockSkillsCombatLevel",
  "skyblockSkillsForagingLevel",
  "skyblockSkillsFishingLevel",
  "skyblockSkillsEnchantingLevel",
  "skyblockSkillsAlchemyLevel",
  "skyblockSkillsCarpentryLevel",
  "skyblockSkillsRunecraftingLevel",
  "skyblockSkillsSocialLevel",
  "skyblockSkillsTamingLevel",

  "skyblockSkillsFarmingXp",
  "skyblockSkillsMiningXp",
  "skyblockSkillsCombatXp",
  "skyblockSkillsForagingXp",
  "skyblockSkillsFishingXp",
  "skyblockSkillsEnchantingXp",
  "skyblockSkillsAlchemyXp",
  "skyblockSkillsCarpentryXp",
  "skyblockSkillsRunecraftingXp",
  "skyblockSkillsSocialXp",
  "skyblockSkillsTamingXp",

  "skyblockSlayerZombieLevel",
  "skyblockSlayerSpiderLevel",
  "skyblockSlayerWolfLevel",
  "skyblockSlayerEndermanLevel",
  "skyblockSlayerBlazeLevel",
  "skyblockSlayerVampireLevel",

  "skyblockSlayerZombieXp",
  "skyblockSlayerSpiderXp",
  "skyblockSlayerWolfXp",
  "skyblockSlayerEndermanXp",
  "skyblockSlayerBlazeXp",
  "skyblockSlayerVampireXp",

  "skyblockDungeonsSecrets",
  "skyblockDungeonsXp",
  "skyblockDungeonsLevel",

  "skyblockDungeonsClassAverageLevel",
  "skyblockDungeonsClassHealerLevel",
  "skyblockDungeonsClassMageLevel",
  "skyblockDungeonsClassBerserkLevel",
  "skyblockDungeonsClassArcherLevel",
  "skyblockDungeonsClassTankLevel",

  "skyblockDungeonsClassHealerXp",
  "skyblockDungeonsClassMageXp",
  "skyblockDungeonsClassBerserkXp",
  "skyblockDungeonsClassArcherXp",
  "skyblockDungeonsClassTankXp",

  "skyblockDungeonsEssenceDiamond",
  "skyblockDungeonsEssenceDragon",
  "skyblockDungeonsEssenceSpider",
  "skyblockDungeonsEssenceWither",
  "skyblockDungeonsEssenceUndead",
  "skyblockDungeonsEssenceGold",
  "skyblockDungeonsEssenceIce",
  "skyblockDungeonsEssenceCrimson",

  "skyblockCrimsonIsleReputationBarbarian",
  "skyblockCrimsonIsleReputationMage",

  "skyblockCrimsonIsleKuudraBasic",
  "skyblockCrimsonIsleKuudraHot",
  "skyblockCrimsonIsleKuudraBurning",
  "skyblockCrimsonIsleKuudraFiery",
  "skyblockCrimsonIsleKuudraInfernal",

  "skyblockNetworth",
  "skyblockNetwrothArmor",
  "skyblockNetwrothEquipment",
  "skyblockNetwrothWardrobe",
  "skyblockNetwrothInventory",
  "skyblockNetwrothEnderchest",
  "skyblockNetwrothAccessories",
  "skyblockNetwrothPersonalVault",
  "skyblockNetwrothFishingBag",
  "skyblockNetwrothStorage",
  "skyblockNetwrothMuseum",
  "skyblockNetwrothSacks",
  "skyblockNetwrothEssence",
  "skyblockNetwrothPets",

  "skyblockNetworthNetworthUnsoulbound",
  "skyblockNetwrothArmorUnsoulbound",
  "skyblockNetwrothEquipmentUnsoulbound",
  "skyblockNetwrothWardrobeUnsoulbound",
  "skyblockNetwrothInventoryUnsoulbound",
  "skyblockNetwrothEnderchestUnsoulbound",
  "skyblockNetwrothAccessoriesUnsoulbound",
  "skyblockNetwrothPersonalVaultUnsoulbound",
  "skyblockNetwrothFishingBagUnsoulbound",
  "skyblockNetwrothStorageUnsoulbound",
  "skyblockNetwrothMuseumUnsoulbound",
  "skyblockNetwrothSacksUnsoulbound",
  "skyblockNetwrothEssenceUnsoulbound",
  "skyblockNetwrothPetsUnsoulbound",

  "skyblockChocolateFactoryLevel",
  "skyblockChocolateFactoryChocolateCurrent",
  "skyblockChocolateFactoryChocolateSincePrestige",
  "skyblockChocolateFactoryChocolateTotal",

  "skyblockChocolateFactoryEmployeeBro",
  "skyblockChocolateFactoryEmployeeCousin",
  "skyblockChocolateFactoryEmployeeSis",
  "skyblockChocolateFactoryEmployeeFather",
  "skyblockChocolateFactoryEmployeeGrandma",
  "skyblockChocolateFactoryEmployeeUncle",
  "skyblockChocolateFactoryEmployeeDog",

  "skyblockJacobMedalsGold",
  "skyblockJacobMedalsSilver",
  "skyblockJacobMedalsBronze",

  "skyblockJacobPerksLevelCap",
  "skyblockJacobPerksDoubleDrops",

  "skyblockJacobPersonalBestNetherWart",
  "skyblockJacobPersonalBestCocoBeans",
  "skyblockJacobPersonalBestMushroom",
  "skyblockJacobPersonalBestWheat",
  "skyblockJacobPersonalBestPotato",
  "skyblockJacobPersonalBestPumpkin",
  "skyblockJacobPersonalBestCarrot",
  "skyblockJacobPersonalBestCactus",
  "skyblockJacobPersonalBestMelon",
  "skyblockJacobPersonalBestSugarCane"
] as const;
export const PlayerVariableStatsKeys = [...PlayerVariableStatsKeysString, ...PlayerVariableStatsKeysNumber] as const;
